### ISSUE TITLE
'NoneType' found when run enumerate(dataloader) in zero-shot tutorial

### ISSUE THREAD

**Issue by xcxtx8** [PharMolix/LangCell#4]
Hello,

Thank you guys for developing such innovating tools!

When I was trying to run your zero-shot.ipytnb tutorial with the existly same input data, I got this error when run 

with torch.no_grad():
    for i, d in tqdm(enumerate(dataloader)):

It returns

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

I tried to locate the issue and the problem might lies in self.tokenizer.cls_token_id

![image](https://github.com/PharMolix/LangCell/assets/28893500/60d8f57f-9371-4d62-a5e9-66ca20a3fee3)
![image](https://github.com/PharMolix/LangCell/assets/28893500/33a0941d-fa30-4d47-a763-72efc3d679f9)

Is there any way to fix that? Thank you !!!

Best,
Chenxi

**Comment by toycat-I** [comment]
Hi Chenxi, 

The bug was caused by the absence of the *\<cls\>* token in Geneformer's token dictionary. We have fixed this bug in the latest version by updating utils.py. 

Thank you for your interest in LangCell and for your help in improving the project! If you have any other questions, please feel free to contact us~^_^

Best,
Suyuan
